
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: clone-build-push-argo-eventlistener
spec:
  serviceAccountName: tekton-sa
  triggers:
    - name: clone-build-push-trigger
      interceptors:
        - ref:
            name: "github"
          params:
          - name: "eventTypes"
            value: ["push","pull_request"]
      bindings:
      - ref: clone-build-push-deploy-argotrigger-binding
      template:
        ref: clone-build-push-deploy-argo-trigger-template
