apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec:
  description: | 
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
  - name: repo-url
    type: string
  - name: image-reference
    type: string
  - name: tag-image
    type: string
  - name: dockerfile
    type: string
  - name: context
    type: string
  - name: application-name
    type: string
  workspaces:
  - name: shared-data
  - name: docker-credentials
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: build-push
    runAfter: ["fetch-source"]
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: docker-credentials
    params:
    - name: IMAGE
      value: $(params.image-reference):$(params.tag-image)
    - name: DOCKERFILE
      value: $(params.dockerfile)
    - name: CONTEXT
      value: $(params.context)
  - name: sync-application
    runAfter: ["build-push"]
    taskRef:
        name: argocd-task-sync-and-wait
    params:
        - name: application-name
          value: $(params.application-name)
        - name: tag-image
          value: $(params.tag-image)
        - name: flags
          value: --insecure # needed in this example only because the Argo CD server is locally hosted
