# Workload Identity is used to bind the kubernetes service account to GCP service account
# https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
# These commands are used:

# gcloud iam service-accounts create tekton-sa
# gcloud artifacts repositories add-iam-policy-binding hello-tekton-image \
  # --location europe-west1 \
  # --member=serviceAccount:tekton-sa@poc-franck.iam.gserviceaccount.com \
  # --role=roles/artifactregistry.reader \
  # --role=roles/artifactregistry.writer

# gcloud iam service-accounts add-iam-policy-binding   --role roles/iam.workloadIdentityUser   --member "serviceAccount:poc-franck.svc.id.goog[default/tekton-sa]"   tekton-sa@poc-franck.iam.gserviceaccount.com

############# DO NOT WORK AS WE ARE IN FREE TRIAL OF GCP.
############# I used docker-credentials secret to authenticate instead of workload-identity

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa
  annotations:
    iam.gke.io/gcp-service-account: tekton-sa@poc-franck.iam.gserviceaccount.com

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-example-eventlistener-binding
subjects:
- kind: ServiceAccount
  name: tekton-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-example-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles