apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  ARGOCD_SERVER: argocd-server.argocd.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
data:
  # choose one of username/password or auth token
  ARGOCD_USERNAME: YWRtaW4K
  ARGOCD_PASSWORD: YWRtaW4xMjM0Cg==
 # ARGOCD_AUTH_TOKEN: <token>